version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/bookstore-api-gateway/Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/bookstore_db'
      USERS_SERVICE_HOST: users-service
      BOOKS_SERVICE_HOST: books-service
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    depends_on:
      users-service:
        condition: service_started
      books-service:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - nestjs-network
    volumes:
      - .:/app
      - /app/node_modules

  users-service:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/bookstore_db'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      USERS_SERVICE_HOST: users-service
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - nestjs-network
    volumes:
      - .:/app
      - /app/node_modules

  books-service:
    build:
      context: .
      dockerfile: ./apps/books/Dockerfile.dev
    ports:
      - '3002:3002'
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/bookstore_db'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      BOOKS_SERVICE_HOST: books-service
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - nestjs-network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore_db
    networks:
      - nestjs-network
    restart: always
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    networks:
      - nestjs-network
    restart: always
    ports:
      - '6379:6379'

volumes:
  db-data:

networks:
  nestjs-network:
    driver: bridge
