FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
COPY nest-cli.json tsconfig*.json ./

RUN npm install

COPY apps ./apps
COPY prisma ./prisma

RUN npm install -g @nestjs/cli

EXPOSE 3000

# Run database migrations and start development server
CMD ["npm", "run", "migrate:start:dev:bookstore-api-gateway"]
